/*
 * Portions of this file are adapted from the Buster browser extension
 * Copyright (C) 2018-2024 Buster contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

export const captchaGoogleSpeechApiLangCodes = {
  ar: 'ar-SA',
  af: 'af-ZA',
  am: 'am-ET',
  hy: 'hy-AM',
  az: 'az-AZ',
  eu: 'eu-ES',
  bn: 'bn-BD',
  bg: 'bg-BG',
  ca: 'ca-ES',
  'zh-HK': 'cmn-Hans-HK',
  'zh-CN': 'cmn-Hans-CN',
  'zh-TW': 'cmn-Hant-TW',
  hr: 'hr-HR',
  cs: 'cs-CZ',
  da: 'da-DK',
  nl: 'nl-NL',
  'en-GB': 'en-GB',
  en: 'en-US',
  et: 'et-EE',
  fil: 'fil-PH',
  fi: 'fi-FI',
  fr: 'fr-FR',
  'fr-CA': 'fr-CA',
  gl: 'gl-ES',
  ka: 'ka-GE',
  de: 'de-DE',
  'de-AT': 'de-DE',
  'de-CH': 'de-DE',
  el: 'el-GR',
  gu: 'gu-IN',
  iw: 'he-IL',
  hi: 'hi-IN',
  hu: 'hu-HU',
  is: 'is-IS',
  id: 'id-ID',
  it: 'it-IT',
  ja: 'ja-JP',
  kn: 'kn-IN',
  ko: 'ko-KR',
  lo: 'lo-LA',
  lv: 'lv-LV',
  lt: 'lt-LT',
  ms: 'ms-MY',
  ml: 'ml-IN',
  mr: 'mr-IN',
  mn: 'mn-MN',
  no: 'nb-NO',
  fa: 'fa-IR',
  pl: 'pl-PL',
  pt: 'pt-PT',
  'pt-BR': 'pt-BR',
  'pt-PT': 'pt-PT',
  ro: 'ro-RO',
  ru: 'ru-RU',
  sr: 'sr-RS',
  si: 'si-LK',
  sk: 'sk-SK',
  sl: 'sl-SI',
  es: 'es-ES',
  'es-419': 'es-MX',
  sw: 'sw-TZ',
  sv: 'sv-SE',
  ta: 'ta-IN',
  te: 'te-IN',
  th: 'th-TH',
  tr: 'tr-TR',
  uk: 'uk-UA',
  ur: 'ur-IN',
  vi: 'vi-VN',
  zu: 'zu-ZA'
};

export const captchaIbmSpeechApiLangCodes = {
  ar: 'ar-MS_Telephony',
  af: '',
  am: '',
  hy: '',
  az: '',
  eu: '',
  bn: '',
  bg: '',
  ca: '',
  'zh-HK': '',
  'zh-CN': 'zh-CN_Telephony',
  'zh-TW': 'zh-CN_Telephony',
  hr: '',
  cs: 'cs-CZ_Telephony',
  da: '',
  nl: 'nl-NL_Multimedia',
  'en-GB': 'en-GB_Multimedia',
  en: 'en-US_Multimedia',
  et: '',
  fil: '',
  fi: '',
  fr: 'fr-FR_Multimedia',
  'fr-CA': 'fr-CA_Multimedia',
  gl: '',
  ka: '',
  de: 'de-DE_Multimedia',
  'de-AT': 'de-DE_Multimedia',
  'de-CH': 'de-DE_Multimedia',
  el: '',
  gu: '',
  iw: '',
  hi: 'hi-IN_Telephony',
  hu: '',
  is: '',
  id: '',
  it: 'it-IT_Multimedia',
  ja: 'ja-JP_Multimedia',
  kn: '',
  ko: 'ko-KR_Multimedia',
  lo: '',
  lv: '',
  lt: '',
  ms: '',
  ml: '',
  mr: '',
  mn: '',
  no: '',
  fa: '',
  pl: '',
  pt: 'pt-BR_Multimedia',
  'pt-BR': 'pt-BR_Multimedia',
  'pt-PT': 'pt-BR_Multimedia',
  ro: '',
  ru: '',
  sr: '',
  si: '',
  sk: '',
  sl: '',
  es: 'es-ES_Multimedia',
  'es-419': 'es-LA_Telephony',
  sw: '',
  sv: 'sv-SE_Telephony',
  ta: '',
  te: '',
  th: '',
  tr: '',
  uk: '',
  ur: '',
  vi: '',
  zu: ''
};

export const captchaMicrosoftSpeechApiLangCodes = {
  ar: 'ar-EG',
  af: 'af-ZA',
  am: 'am-ET',
  hy: 'hy-AM',
  az: 'az-AZ',
  eu: 'eu-ES',
  bn: 'bn-IN',
  bg: 'bg-BG',
  ca: 'ca-ES',
  'zh-HK': 'zh-HK',
  'zh-CN': 'zh-CN',
  'zh-TW': 'zh-TW',
  hr: 'hr-HR',
  cs: 'cs-CZ',
  da: 'da-DK',
  nl: 'nl-NL',
  'en-GB': 'en-GB',
  en: 'en-US',
  et: 'et-EE',
  fil: 'fil-PH',
  fi: 'fi-FI',
  fr: 'fr-FR',
  'fr-CA': 'fr-CA',
  gl: 'gl-ES',
  ka: 'ka-GE',
  de: 'de-DE',
  'de-AT': 'de-AT',
  'de-CH': 'de-CH',
  el: 'el-GR',
  gu: 'gu-IN',
  iw: 'he-IL',
  hi: 'hi-IN',
  hu: 'hu-HU',
  is: 'is-IS',
  id: 'id-ID',
  it: 'it-IT',
  ja: 'ja-JP',
  kn: 'kn-IN',
  ko: 'ko-KR',
  lo: 'lo-LA',
  lv: 'lv-LV',
  lt: 'lt-LT',
  ms: 'ms-MY',
  ml: 'ml-IN',
  mr: 'mr-IN',
  mn: 'mn-MN',
  no: 'nb-NO',
  fa: 'fa-IR',
  pl: 'pl-PL',
  pt: 'pt-PT',
  'pt-BR': 'pt-BR',
  'pt-PT': 'pt-PT',
  ro: 'ro-RO',
  ru: 'ru-RU',
  sr: 'sr-RS',
  si: 'si-LK',
  sk: 'sk-SK',
  sl: 'sl-SI',
  es: 'es-ES',
  'es-419': 'es-MX',
  sw: 'sw-TZ',
  sv: 'sv-SE',
  ta: 'ta-IN',
  te: 'te-IN',
  th: 'th-TH',
  tr: 'tr-TR',
  uk: 'uk-UA',
  ur: 'ur-IN',
  vi: 'vi-VN',
  zu: 'zu-ZA'
};

export const captchaWitSpeechApiLangCodes = {
  ar: 'arabic',
  af: '',
  am: '',
  hy: '',
  az: '',
  eu: '',
  bn: 'bengali',
  bg: '',
  ca: '',
  'zh-HK': '',
  'zh-CN': 'chinese',
  'zh-TW': 'chinese',
  hr: '',
  cs: '',
  da: '',
  nl: 'dutch',
  'en-GB': 'english',
  en: 'english',
  et: '',
  fil: '',
  fi: 'finnish',
  fr: 'french',
  'fr-CA': 'french',
  gl: '',
  ka: '',
  de: 'german',
  'de-AT': 'german',
  'de-CH': 'german',
  el: '',
  gu: '',
  iw: '',
  hi: 'hindi',
  hu: '',
  is: '',
  id: 'indonesian',
  it: 'italian',
  ja: 'japanese',
  kn: 'kannada',
  ko: 'korean',
  lo: '',
  lv: '',
  lt: '',
  ms: 'malay',
  ml: 'malayalam',
  mr: 'marathi',
  mn: '',
  no: '',
  fa: '',
  pl: 'polish',
  pt: 'portuguese',
  'pt-BR': 'portuguese',
  'pt-PT': 'portuguese',
  ro: '',
  ru: 'russian',
  sr: '',
  si: 'sinhala',
  sk: '',
  sl: '',
  es: 'spanish',
  'es-419': 'spanish',
  sw: '',
  sv: 'swedish',
  ta: 'tamil',
  te: '',
  th: 'thai',
  tr: 'turkish',
  uk: '',
  ur: 'urdu',
  vi: 'vietnamese',
  zu: ''
};

export const microsoftSpeechApiRegions = [
  'southafricanorth',
  'eastasia',
  'southeastasia',
  'australiaeast',
  'centralindia',
  'japaneast',
  'japanwest',
  'koreacentral',
  'canadacentral',
  'northeurope',
  'westeurope',
  'francecentral',
  'germanywestcentral',
  'norwayeast',
  'swedencentral',
  'switzerlandnorth',
  'switzerlandwest',
  'uksouth',
  'uaenorth',
  'brazilsouth',
  'qatarcentral',
  'centralus',
  'eastus',
  'eastus2',
  'northcentralus',
  'southcentralus',
  'westcentralus',
  'westus',
  'westus2',
  'westus3'
];

export function getSupportedLanguages() {
  return Object.keys(captchaGoogleSpeechApiLangCodes);
}
